package main

import (
	"database/sql"
	"fmt"
	"log"
	"os"
	"strings"

	_ "modernc.org/sqlite"
)

// SQLite → Oracle 전체 이관 SQL 생성 도구
// 사용법:
//   cd backend
//   go run ./cmd/migrate
//
// 환경변수:
//   SQLITE_PATH   - SQLite DB 경로 (기본: ./jugan.db)
//   OUTPUT_PATH   - 출력 SQL 파일 경로 (기본: ./migration.sql)
//   TABLESPACE    - Oracle 테이블스페이스 (기본: jugan_tablespace)
//   INDEXSPACE    - Oracle 인덱스스페이스 (기본: jugan_indexspace)
//
// 결과: migration.sql 파일 생성
// Oracle에서 SQL Developer 또는 sqlplus로 실행하면 테이블 생성 + 데이터 이관 완료

func main() {
	sqlitePath := os.Getenv("SQLITE_PATH")
	if sqlitePath == "" {
		sqlitePath = "./jugan.db"
	}
	outPath := os.Getenv("OUTPUT_PATH")
	if outPath == "" {
		outPath = "./migration.sql"
	}
	tablespace := os.Getenv("TABLESPACE")
	if tablespace == "" {
		tablespace = "jugan_tablespace"
	}
	indexspace := os.Getenv("INDEXSPACE")
	if indexspace == "" {
		indexspace = "jugan_indexspace"
	}

	db, err := sql.Open("sqlite", sqlitePath)
	if err != nil {
		log.Fatalf("SQLite open failed: %v", err)
	}
	defer db.Close()
	db.Exec("PRAGMA journal_mode=WAL")
	db.Exec("PRAGMA foreign_keys=ON")
	log.Printf("SQLite connected: %s", sqlitePath)

	f, err := os.Create(outPath)
	if err != nil {
		log.Fatalf("Failed to create output file: %v", err)
	}
	defer f.Close()

	w := func(format string, args ...any) {
		fmt.Fprintf(f, format+"\n", args...)
	}

	w("-- ============================================")
	w("-- Weeky: SQLite -> Oracle Migration Script")
	w("-- Source: %s", sqlitePath)
	w("-- Tablespace: %s / Indexspace: %s", tablespace, indexspace)
	w("-- ============================================")
	w("-- 이 파일 하나로 테이블 생성 + 데이터 이관이 완료됩니다.")
	w("-- SQL Developer 또는 sqlplus에서 실행하세요.")
	w("-- ============================================")
	w("")

	// ========== PART 1: DDL (테이블 생성) ==========
	w("-- ============================================")
	w("-- PART 1: 테이블 생성 (DDL)")
	w("-- ============================================")
	w("")

	// migrations_ 테이블
	w("-- migrations_ 테이블")
	w("CREATE TABLE migrations_ (")
	w("    version NUMBER PRIMARY KEY,")
	w("    applied_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP")
	w(") TABLESPACE %s;", tablespace)
	w("")

	// users
	w("-- users 테이블")
	w("CREATE TABLE users (")
	w("    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,")
	w("    email VARCHAR2(255) NOT NULL,")
	w("    password_hash VARCHAR2(255) NOT NULL,")
	w("    name VARCHAR2(255) NOT NULL,")
	w("    is_admin NUMBER(1) DEFAULT 0 NOT NULL,")
	w("    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,")
	w("    CONSTRAINT uq_users_email UNIQUE (email)")
	w(") TABLESPACE %s;", tablespace)
	w("")

	// invite_codes
	w("-- invite_codes 테이블")
	w("CREATE TABLE invite_codes (")
	w("    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,")
	w("    code VARCHAR2(255) NOT NULL,")
	w("    created_by NUMBER NOT NULL REFERENCES users(id),")
	w("    used_by NUMBER REFERENCES users(id),")
	w("    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,")
	w("    used_at TIMESTAMP,")
	w("    CONSTRAINT uq_invite_codes_code UNIQUE (code)")
	w(") TABLESPACE %s;", tablespace)
	w("")

	// templates
	w("-- templates 테이블")
	w("CREATE TABLE templates (")
	w("    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,")
	w("    name VARCHAR2(255) NOT NULL,")
	w("    style CLOB DEFAULT '{}',")
	w("    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP")
	w(") TABLESPACE %s;", tablespace)
	w("")

	// reports (v1 + v2 + v3 합침)
	w("-- reports 테이블")
	w("CREATE TABLE reports (")
	w("    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,")
	w("    user_id NUMBER DEFAULT 0 NOT NULL,")
	w("    team_name VARCHAR2(255) NOT NULL,")
	w("    author_name VARCHAR2(255) NOT NULL,")
	w("    report_date VARCHAR2(10) NOT NULL,")
	w("    this_week CLOB DEFAULT '[]',")
	w("    next_week CLOB DEFAULT '[]',")
	w("    issues VARCHAR2(4000) DEFAULT '',")
	w("    notes VARCHAR2(4000) DEFAULT '',")
	w("    next_issues VARCHAR2(4000) DEFAULT '',")
	w("    next_notes VARCHAR2(4000) DEFAULT '',")
	w("    template_id NUMBER,")
	w("    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP")
	w(") TABLESPACE %s;", tablespace)
	w("")

	// configs
	w("-- configs 테이블")
	w("CREATE TABLE configs (")
	w("    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,")
	w("    user_id NUMBER DEFAULT 0 NOT NULL,")
	w("    key VARCHAR2(255) NOT NULL,")
	w("    value VARCHAR2(4000) DEFAULT '',")
	w("    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,")
	w("    CONSTRAINT uq_configs_user_key UNIQUE (user_id, key)")
	w(") TABLESPACE %s;", tablespace)
	w("")

	// teams
	w("-- teams 테이블")
	w("CREATE TABLE teams (")
	w("    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,")
	w("    name VARCHAR2(255) NOT NULL,")
	w("    description VARCHAR2(4000) DEFAULT '',")
	w("    created_by NUMBER NOT NULL REFERENCES users(id),")
	w("    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP")
	w(") TABLESPACE %s;", tablespace)
	w("")

	// team_members
	w("-- team_members 테이블")
	w("CREATE TABLE team_members (")
	w("    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,")
	w("    team_id NUMBER NOT NULL REFERENCES teams(id) ON DELETE CASCADE,")
	w("    user_id NUMBER NOT NULL REFERENCES users(id),")
	w("    role VARCHAR2(50) DEFAULT 'member' NOT NULL,")
	w("    role_code VARCHAR2(10) DEFAULT 'S' NOT NULL,")
	w("    joined_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,")
	w("    CONSTRAINT uq_team_members UNIQUE (team_id, user_id)")
	w(") TABLESPACE %s;", tablespace)
	w("")

	// report_submissions
	w("-- report_submissions 테이블")
	w("CREATE TABLE report_submissions (")
	w("    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,")
	w("    report_id NUMBER NOT NULL REFERENCES reports(id),")
	w("    team_id NUMBER NOT NULL REFERENCES teams(id),")
	w("    user_id NUMBER NOT NULL REFERENCES users(id),")
	w("    status VARCHAR2(50) DEFAULT 'draft' NOT NULL,")
	w("    submitted_at TIMESTAMP,")
	w("    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,")
	w("    CONSTRAINT uq_report_submissions UNIQUE (report_id, team_id)")
	w(") TABLESPACE %s;", tablespace)
	w("")

	// team_projects (v5 + v6 합침)
	w("-- team_projects 테이블")
	w("CREATE TABLE team_projects (")
	w("    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,")
	w("    team_id NUMBER NOT NULL REFERENCES teams(id) ON DELETE CASCADE,")
	w("    name VARCHAR2(255) NOT NULL,")
	w("    client VARCHAR2(255) DEFAULT '',")
	w("    is_active NUMBER(1) DEFAULT 1,")
	w("    sort_order NUMBER DEFAULT 0,")
	w("    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,")
	w("    CONSTRAINT uq_team_projects_name_client UNIQUE (team_id, name, client)")
	w(") TABLESPACE %s;", tablespace)
	w("")

	// consolidated_edits
	w("-- consolidated_edits 테이블")
	w("CREATE TABLE consolidated_edits (")
	w("    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,")
	w("    team_id NUMBER NOT NULL REFERENCES teams(id) ON DELETE CASCADE,")
	w("    report_date VARCHAR2(10) NOT NULL,")
	w("    data CLOB NOT NULL,")
	w("    updated_by NUMBER NOT NULL,")
	w("    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,")
	w("    CONSTRAINT uq_consolidated_edits UNIQUE (team_id, report_date)")
	w(") TABLESPACE %s;", tablespace)
	w("")

	// 마이그레이션 버전 기록
	w("-- 마이그레이션 버전 기록 (v1~v7 적용 완료)")
	for v := 1; v <= 7; v++ {
		w("INSERT INTO migrations_ (version) VALUES (%d);", v)
	}
	w("COMMIT;")
	w("")

	// ========== PART 2: 데이터 INSERT ==========
	w("-- ============================================")
	w("-- PART 2: 데이터 이관 (SQLite -> Oracle)")
	w("-- ============================================")
	w("")

	total := 0
	total += dumpUsers(db, w)
	total += dumpInviteCodes(db, w)
	total += dumpTemplates(db, w)
	total += dumpReports(db, w)
	total += dumpConfigs(db, w)
	total += dumpTeams(db, w)
	total += dumpTeamMembers(db, w)
	total += dumpReportSubmissions(db, w)
	total += dumpTeamProjects(db, w)
	total += dumpConsolidatedEdits(db, w)

	w("COMMIT;")
	w("")

	// ========== PART 3: Identity 시퀀스 리셋 ==========
	w("-- ============================================")
	w("-- PART 3: Identity 시퀀스 리셋")
	w("-- ============================================")
	idTables := []string{
		"users", "invite_codes", "templates", "reports", "configs",
		"teams", "team_members", "report_submissions", "team_projects", "consolidated_edits",
	}
	w("DECLARE")
	w("  v_max NUMBER;")
	w("BEGIN")
	for _, t := range idTables {
		w("  SELECT NVL(MAX(id), 0) + 1 INTO v_max FROM %s;", t)
		w("  EXECUTE IMMEDIATE 'ALTER TABLE %s MODIFY (id GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH ' || v_max || '))';", t)
	}
	w("END;")
	w("/")
	w("")
	w("-- ============================================")
	w("-- Migration complete! Total: %d rows", total)
	w("-- ============================================")

	log.Printf("Output: %s (%d total rows)", outPath, total)
	log.Println("Done! Oracle에서 이 SQL 파일을 실행하세요.")
}

// esc escapes a string for Oracle SQL literal (single quotes)
func esc(s string) string {
	return strings.ReplaceAll(s, "'", "''")
}

// ts formats a SQLite datetime string as Oracle TO_TIMESTAMP()
func ts(s string) string {
	if s == "" {
		return "NULL"
	}
	// SQLite stores timestamps in various formats: "2026-02-20 01:28:33", "2026-02-20T01:28:33Z"
	// Normalize to "YYYY-MM-DD HH24:MI:SS" for Oracle
	normalized := strings.ReplaceAll(s, "T", " ")
	normalized = strings.TrimSuffix(normalized, "Z")
	// Trim sub-seconds if present
	if idx := strings.Index(normalized, "."); idx != -1 {
		normalized = normalized[:idx]
	}
	return fmt.Sprintf("TO_TIMESTAMP('%s', 'YYYY-MM-DD HH24:MI:SS')", esc(normalized))
}

func nullTS(s *string) string {
	if s == nil || *s == "" {
		return "NULL"
	}
	return ts(*s)
}

func nullInt(v *int64) string {
	if v == nil {
		return "NULL"
	}
	return fmt.Sprintf("%d", *v)
}

// strVal formats a string as Oracle literal, splitting long strings for CLOB safety
func strVal(s string) string {
	if s == "" {
		return "''"
	}
	escaped := esc(s)
	if len(escaped) <= 3900 {
		return fmt.Sprintf("'%s'", escaped)
	}
	var parts []string
	for len(escaped) > 0 {
		end := 3900
		if end > len(escaped) {
			end = len(escaped)
		}
		parts = append(parts, fmt.Sprintf("'%s'", escaped[:end]))
		escaped = escaped[end:]
	}
	return strings.Join(parts, " || ")
}

func dumpUsers(db *sql.DB, w func(string, ...any)) int {
	rows, err := db.Query("SELECT id, email, password_hash, name, is_admin, created_at FROM users ORDER BY id")
	if err != nil {
		log.Printf("  Skip users: %v", err)
		return 0
	}
	defer rows.Close()

	w("-- Data: users")
	var count int
	for rows.Next() {
		var id, isAdmin int64
		var email, passwordHash, name, createdAt string
		if err := rows.Scan(&id, &email, &passwordHash, &name, &isAdmin, &createdAt); err != nil {
			log.Printf("  Error scanning user: %v", err)
			continue
		}
		w("INSERT INTO users (id, email, password_hash, name, is_admin, created_at) VALUES (%d, '%s', '%s', '%s', %d, %s);",
			id, esc(email), esc(passwordHash), esc(name), isAdmin, ts(createdAt))
		count++
	}
	w("")
	log.Printf("  users: %d rows", count)
	return count
}

func dumpInviteCodes(db *sql.DB, w func(string, ...any)) int {
	rows, err := db.Query("SELECT id, code, created_by, used_by, created_at, used_at FROM invite_codes ORDER BY id")
	if err != nil {
		log.Printf("  Skip invite_codes: %v", err)
		return 0
	}
	defer rows.Close()

	w("-- Data: invite_codes")
	var count int
	for rows.Next() {
		var id, createdBy int64
		var code, createdAt string
		var usedBy *int64
		var usedAt *string
		if err := rows.Scan(&id, &code, &createdBy, &usedBy, &createdAt, &usedAt); err != nil {
			log.Printf("  Error scanning invite_code: %v", err)
			continue
		}
		w("INSERT INTO invite_codes (id, code, created_by, used_by, created_at, used_at) VALUES (%d, '%s', %d, %s, %s, %s);",
			id, esc(code), createdBy, nullInt(usedBy), ts(createdAt), nullTS(usedAt))
		count++
	}
	w("")
	log.Printf("  invite_codes: %d rows", count)
	return count
}

func dumpTemplates(db *sql.DB, w func(string, ...any)) int {
	rows, err := db.Query("SELECT id, name, style, created_at FROM templates ORDER BY id")
	if err != nil {
		log.Printf("  Skip templates: %v", err)
		return 0
	}
	defer rows.Close()

	w("-- Data: templates")
	var count int
	for rows.Next() {
		var id int64
		var name, style, createdAt string
		if err := rows.Scan(&id, &name, &style, &createdAt); err != nil {
			log.Printf("  Error scanning template: %v", err)
			continue
		}
		w("INSERT INTO templates (id, name, style, created_at) VALUES (%d, '%s', %s, %s);",
			id, esc(name), strVal(style), ts(createdAt))
		count++
	}
	w("")
	log.Printf("  templates: %d rows", count)
	return count
}

func dumpReports(db *sql.DB, w func(string, ...any)) int {
	// 신규 스키마 먼저 시도, 실패하면 레거시
	rows, err := db.Query(`SELECT id, user_id, team_name, author_name, report_date,
		this_week, next_week, issues, notes, next_issues, next_notes, template_id, created_at
		FROM reports ORDER BY id`)
	fullSchema := true
	if err != nil {
		rows, err = db.Query(`SELECT id, team_name, author_name, report_date,
			this_week, next_week, issues, template_id, created_at
			FROM reports ORDER BY id`)
		fullSchema = false
		if err != nil {
			log.Printf("  Skip reports: %v", err)
			return 0
		}
	}
	defer rows.Close()

	w("-- Data: reports")
	var count int
	for rows.Next() {
		var id, userID, templateID int64
		var teamName, authorName, reportDate, thisWeek, nextWeek string
		var issues, notes, nextIssues, nextNotes, createdAt string
		if fullSchema {
			if err := rows.Scan(&id, &userID, &teamName, &authorName, &reportDate,
				&thisWeek, &nextWeek, &issues, &notes, &nextIssues, &nextNotes, &templateID, &createdAt); err != nil {
				log.Printf("  Error scanning report: %v", err)
				continue
			}
		} else {
			if err := rows.Scan(&id, &teamName, &authorName, &reportDate,
				&thisWeek, &nextWeek, &issues, &templateID, &createdAt); err != nil {
				log.Printf("  Error scanning report: %v", err)
				continue
			}
		}
		w("INSERT INTO reports (id, user_id, team_name, author_name, report_date, this_week, next_week, issues, notes, next_issues, next_notes, template_id, created_at) VALUES (%d, %d, '%s', '%s', '%s', %s, %s, %s, %s, %s, %s, %d, %s);",
			id, userID, esc(teamName), esc(authorName), esc(reportDate),
			strVal(thisWeek), strVal(nextWeek), strVal(issues), strVal(notes),
			strVal(nextIssues), strVal(nextNotes), templateID, ts(createdAt))
		count++
	}
	w("")
	log.Printf("  reports: %d rows", count)
	return count
}

func dumpConfigs(db *sql.DB, w func(string, ...any)) int {
	// 신규 스키마(user_id 있음) 먼저 시도, 실패하면 레거시
	rows, err := db.Query("SELECT id, user_id, key, value, updated_at FROM configs ORDER BY id")
	hasUserID := true
	if err != nil {
		rows, err = db.Query("SELECT id, key, value, updated_at FROM configs ORDER BY id")
		hasUserID = false
		if err != nil {
			log.Printf("  Skip configs: %v", err)
			return 0
		}
	}
	defer rows.Close()

	w("-- Data: configs (encrypted tokens preserved)")
	var count int
	for rows.Next() {
		var id, userID int64
		var key, value, updatedAt string
		if hasUserID {
			if err := rows.Scan(&id, &userID, &key, &value, &updatedAt); err != nil {
				log.Printf("  Error scanning config: %v", err)
				continue
			}
		} else {
			if err := rows.Scan(&id, &key, &value, &updatedAt); err != nil {
				log.Printf("  Error scanning config: %v", err)
				continue
			}
			userID = 0
		}
		w("INSERT INTO configs (id, user_id, key, value, updated_at) VALUES (%d, %d, '%s', %s, %s);",
			id, userID, esc(key), strVal(value), ts(updatedAt))
		count++
	}
	w("")
	log.Printf("  configs: %d rows (encrypted tokens preserved)", count)
	return count
}

func dumpTeams(db *sql.DB, w func(string, ...any)) int {
	rows, err := db.Query("SELECT id, name, description, created_by, created_at FROM teams ORDER BY id")
	if err != nil {
		log.Printf("  Skip teams: %v", err)
		return 0
	}
	defer rows.Close()

	w("-- Data: teams")
	var count int
	for rows.Next() {
		var id, createdBy int64
		var name, description, createdAt string
		if err := rows.Scan(&id, &name, &description, &createdBy, &createdAt); err != nil {
			log.Printf("  Error scanning team: %v", err)
			continue
		}
		w("INSERT INTO teams (id, name, description, created_by, created_at) VALUES (%d, '%s', %s, %d, %s);",
			id, esc(name), strVal(description), createdBy, ts(createdAt))
		count++
	}
	w("")
	log.Printf("  teams: %d rows", count)
	return count
}

func dumpTeamMembers(db *sql.DB, w func(string, ...any)) int {
	rows, err := db.Query("SELECT id, team_id, user_id, role, role_code, joined_at FROM team_members ORDER BY id")
	if err != nil {
		log.Printf("  Skip team_members: %v", err)
		return 0
	}
	defer rows.Close()

	w("-- Data: team_members")
	var count int
	for rows.Next() {
		var id, teamID, userID int64
		var role, roleCode, joinedAt string
		if err := rows.Scan(&id, &teamID, &userID, &role, &roleCode, &joinedAt); err != nil {
			log.Printf("  Error scanning team_member: %v", err)
			continue
		}
		w("INSERT INTO team_members (id, team_id, user_id, role, role_code, joined_at) VALUES (%d, %d, %d, '%s', '%s', %s);",
			id, teamID, userID, esc(role), esc(roleCode), ts(joinedAt))
		count++
	}
	w("")
	log.Printf("  team_members: %d rows", count)
	return count
}

func dumpReportSubmissions(db *sql.DB, w func(string, ...any)) int {
	rows, err := db.Query("SELECT id, report_id, team_id, user_id, status, submitted_at, created_at FROM report_submissions ORDER BY id")
	if err != nil {
		log.Printf("  Skip report_submissions: %v", err)
		return 0
	}
	defer rows.Close()

	w("-- Data: report_submissions")
	var count int
	for rows.Next() {
		var id, reportID, teamID, userID int64
		var status, createdAt string
		var submittedAt *string
		if err := rows.Scan(&id, &reportID, &teamID, &userID, &status, &submittedAt, &createdAt); err != nil {
			log.Printf("  Error scanning report_submission: %v", err)
			continue
		}
		w("INSERT INTO report_submissions (id, report_id, team_id, user_id, status, submitted_at, created_at) VALUES (%d, %d, %d, %d, '%s', %s, %s);",
			id, reportID, teamID, userID, esc(status), nullTS(submittedAt), ts(createdAt))
		count++
	}
	w("")
	log.Printf("  report_submissions: %d rows", count)
	return count
}

func dumpTeamProjects(db *sql.DB, w func(string, ...any)) int {
	rows, err := db.Query("SELECT id, team_id, name, client, is_active, sort_order, created_at FROM team_projects ORDER BY id")
	if err != nil {
		log.Printf("  Skip team_projects: %v", err)
		return 0
	}
	defer rows.Close()

	w("-- Data: team_projects")
	var count int
	for rows.Next() {
		var id, teamID, isActive, sortOrder int64
		var name, client, createdAt string
		if err := rows.Scan(&id, &teamID, &name, &client, &isActive, &sortOrder, &createdAt); err != nil {
			log.Printf("  Error scanning team_project: %v", err)
			continue
		}
		w("INSERT INTO team_projects (id, team_id, name, client, is_active, sort_order, created_at) VALUES (%d, %d, '%s', '%s', %d, %d, %s);",
			id, teamID, esc(name), esc(client), isActive, sortOrder, ts(createdAt))
		count++
	}
	w("")
	log.Printf("  team_projects: %d rows", count)
	return count
}

func dumpConsolidatedEdits(db *sql.DB, w func(string, ...any)) int {
	rows, err := db.Query("SELECT id, team_id, report_date, data, updated_by, updated_at FROM consolidated_edits ORDER BY id")
	if err != nil {
		log.Printf("  Skip consolidated_edits: %v", err)
		return 0
	}
	defer rows.Close()

	w("-- Data: consolidated_edits")
	var count int
	for rows.Next() {
		var id, teamID, updatedBy int64
		var reportDate, data, updatedAt string
		if err := rows.Scan(&id, &teamID, &reportDate, &data, &updatedBy, &updatedAt); err != nil {
			log.Printf("  Error scanning consolidated_edit: %v", err)
			continue
		}
		w("INSERT INTO consolidated_edits (id, team_id, report_date, data, updated_by, updated_at) VALUES (%d, %d, '%s', %s, %d, %s);",
			id, teamID, esc(reportDate), strVal(data), updatedBy, ts(updatedAt))
		count++
	}
	w("")
	log.Printf("  consolidated_edits: %d rows", count)
	return count
}
